config/routes.rb
Resty::Application.routes.draw do
  

  root :to => 'home#show'

  resources :projects do

    resources :resources
    
    resources :endpoints do
      resources :parameters
    end

    resources :models do
      resources :parameters
    end

  end

  resources :users

  

end

app/models/endpoint.rb
class Endpoint < ActiveRecord::Base
	belongs_to :resource
	belongs_to :project
  has_many :parameters, as: :param_container, dependent: :destroy
end

app/controllers/endpoints_controller.rb
class EndpointsController < ApplicationController
  before_action :set_project
  before_action :set_endpoint, only: [:show, :edit, :update, :destroy]

  # GET /endpoints
  # GET /endpoints.json
  def index
    @endpoints = @project.endpoints.all
  end

  # GET /endpoints/1
  # GET /endpoints/1.json
  def show
    @models = @project.models.all
  end

  # GET /endpoints/new
  def new
    @endpoint = @project.endpoints.new
  end

  # GET /endpoints/1/edit
  def edit
  end

  # POST /endpoints
  # POST /endpoints.json
  def create
    @endpoint = @project.endpoints.new(endpoint_params)

    respond_to do |format|
      if @endpoint.save
        format.html { redirect_to [@project,@endpoint], notice: 'Endpoint was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@project,@endpoint] }
      else
        format.html { render action: 'new' }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /endpoints/1
  # PATCH/PUT /endpoints/1.json
  def update
    respond_to do |format|
      if @endpoint.update(endpoint_params)
        format.html { redirect_to [@project,@endpoint], notice: 'Endpoint was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @endpoint.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /endpoints/1
  # DELETE /endpoints/1.json
  def destroy
    @endpoint.destroy
    respond_to do |format|
      format.html { redirect_to endpoints_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_endpoint
      @endpoint = @project.endpoints.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endpoint_params
      params.require(:endpoint).permit(:description, :method_type, :url, :detail, :resource_id, :project_id)
    end
end

app/helpers/endpoints_helper.rb
module EndpointsHelper
end

app/views/endpoints/_endpoint.html.erb
<tr id="<%= 'endpoint-' + endpoint.id.to_s %>" class="data-row editable">
	<td class="rest-url"><%= link_to endpoint.method_type + ' ' + endpoint.url, [@project,endpoint] %></td>
	<td class="description">
		<span><%= replace_model_link(endpoint.description, @project).html_safe %></span>
	</td>
    <td>
      <div class="edit-btn-div v-hidden">
        <%= link_to 'Edit', 'javascript:;', class: 'edit-btn' %><br>
        <%= link_to 'Delete', [@project,endpoint], method: :delete, remote: true %>
      </div>
    </td>
</tr>
<tr id="<%= 'edit-endpoint-' + endpoint.id.to_s %>" class="edit-row hidden editable">
  <td colspan="3">
    <%= form_for([@project,endpoint], remote:true, authenticity_token: form_authenticity_token) do |f| %>

        <div class="field">
          <%= f.text_field :method_type , class: "type-input-field" , placeholder: "Method Type" %>
          <%= f.text_field :url , class: "url-input-field" , placeholder: "URI" %>
          <%= f.text_area :description , class: "description-input-field" , placeholder: "Description" %>
          <%= f.hidden_field :resource_id, :value => endpoint.resource_id %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
    <button class="cancel-update">Cancel</button>
  </td>
</tr>

app/views/endpoints/_form.html.erb
<%= form_for(@endpoint) do |f| %>
  <% if @endpoint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@endpoint.errors.count, "error") %> prohibited this endpoint from being saved:</h2>

      <ul>
      <% @endpoint.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :method_type %><br>
    <%= f.text_field :method_type %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :detail %><br>
    <%= f.text_area :detail %>
  </div>
  <div class="field">
    <%= f.label :resource_id %><br>
    <%= f.number_field :resource_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/endpoints/create.js.erb
<% if @endpoint.new_record? %>
  $('input#endpoint_name').effect('highlight', { color: 'red' });
<% else %>
  $('#resource_' + <%= @endpoint.resource_id %> + ' .endpoints').append("<%= escape_javascript(render @endpoint) %>");
<% end %>

app/views/endpoints/destroy.js.erb
$("tr#<%= 'endpoint-' + @endpoint.id.to_s %>").fadeOut();
$("tr#<%= 'edit-endpoint-' + @endpoint.id.to_s %>").remove();

app/views/endpoints/edit.html.erb
<h1>Editing endpoint</h1>

<%= render 'form' %>

<%= link_to 'Show', @endpoint %> |
<%= link_to 'Back', endpoints_path %>

app/views/endpoints/index.html.erb
<% javascript_include_tag "application" %>

<h1>Listing endpoints</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Method type</th>
      <th>Url</th>
      <th>Detail</th>
      <th>Resource</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @endpoints.each do |endpoint| %>
      <tr>
        <td><%= endpoint.description %></td>
        <td><%= endpoint.method_type %></td>
        <td><%= endpoint.url %></td>
        <td><%= endpoint.detail %></td>
        <td><%= endpoint.resource_id %></td>
        <td><%= link_to 'Edit', edit_resource_endpoint_path(@resource, endpoint) %></td>
        <td><%= link_to 'Destroy', [@resource,endpoint], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/endpoints/new.html.erb
<h1>New endpoint</h1>

<%= render 'form' %>

<%= link_to 'Back', endpoints_path %>

app/views/endpoints/show.html.erb
<% javascript_include_tag "application" %>

<div id="global-container">
	<h1><%=@endpoint.method_type + ' ' + @endpoint.url%></h1>

	<p>
	  	<strong>Description</strong><br>
	  	<%= replace_model_link(@endpoint.description, @project).html_safe %>
	</p>

	<p>
	  	<strong>Detail</strong><br>
	  	<%= @endpoint.detail %>
	</p>

	<p>
		<strong>Parameters</strong><br>
			<table id="parameters">
                <% @param_container = @endpoint %>
		  		<%= render @endpoint.parameters %>
		  	</table>
		  	<div class="new-form-container hidden">
			      <%= form_for([@project, @endpoint, Parameter.new], remote:true, authenticity_token: form_authenticity_token) do |f| %>
			        <div class="field">
			            <%= f.text_field :name , class: 'name-input-field' , placeholder: 'Name'%>
			            <%= f.text_field :example_value , class: 'example-input-field' , placeholder: 'Example Value'%>
			            <%= f.text_area :description , class: 'description-input-field' , placeholder: 'Description'%>
			        </div>
			        <div class="actions">
			        	<%= f.submit %>
			        </div>
			      <% end %>
			  <button class="cancel-creation">Cancel</button>
			</div>

			<button class="new-row-btn">New Parameter</button>

	</p>
</div>

app/views/endpoints/update.js.erb
$("<%= '#endpoint-' + @endpoint.id.to_s %> .rest-url a").html("<%= @endpoint.method_type + ' ' + @endpoint.url %>")
$("<%= '#endpoint-' + @endpoint.id.to_s %> .description span").html("<%= @endpoint.description %>");
$("<%= '#endpoint-' + @endpoint.id.to_s %>").removeClass('hidden');
$("<%= '#edit-endpoint-' + @endpoint.id.to_s %>").addClass('hidden');