config/routes.rb
Resty::Application.routes.draw do
  

  root :to => 'home#show'

  resources :projects do

    resources :resources
    
    resources :endpoints do
      resources :parameters
    end

    resources :models do
      resources :parameters
    end

  end

  resources :users

  

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<%= div_for resource do %>
  	<table>
	  <caption class="resource-title">
        <div id="<%= 'resource-' + resource.id.to_s %>" class="editable">
            <div>
                <strong class="name"><%=resource.name%></strong> <!-- <%= link_to 'Show', [@project,resource] %> <%= link_to 'Edit', edit_project_resource_path(@project.id, resource.id) %> <%= link_to 'Destroy', [@project,resource], method: :delete, data: { confirm: 'Are you sure?' } %> -->
                <br><span class="description"><%=replace_model_link(resource.description, @project).html_safe%></span>
            </div>
            <div class="edit-btn-div v-hidden">
                <%= link_to 'Edit', 'javascript:;', class: 'edit-btn' %><br>
                <%= link_to 'Delete', [@project,resource], method: :delete, remote: true %>
            </div>
        </div>
        <div id="<%= 'edit-resource-' + resource.id.to_s %>" class="hidden editable">
          <%= form_for([@project, resource], remote:true, authenticity_token: form_authenticity_token) do |f| %>

              <div class="field">
                <%= f.text_field :name , class: 'type-input-field' , placeholder: 'Name' %>
                <%= f.text_area :description , class: 'description-input-field' , placeholder: 'Description' %>
              </div>
              <div class="actions">
                <%= f.submit %>
              </div>
          <% end %>
          <button class="cancel-creation">Cancel</button>
        </div>
	  </caption>
	  <thead>
	    <tr>
	      <th>
	        Endpoints        
	      </th>
	      <th>
	        Description        
	      </th>
          <th>
          </th>
	    </tr>
	  </thead>
	  <tbody class="endpoints">
	  	<%= render resource.endpoints %>
	  </tbody>
	</table>
	<div class="new-form-container hidden">
	      <%= form_for([@project,Endpoint.new], remote:true, authenticity_token: form_authenticity_token) do |f| %>
	        <div class="field">
	            <%= f.text_field :method_type , class: "type-input-field" , placeholder: "Method Type" %>
	            <%= f.text_field :url , class: "url-input-field" , placeholder: "URI" %>
	            <%= f.text_area :description , class: "description-input-field" , placeholder: "Description" %>
	            <%= f.hidden_field :resource_id, :value => resource.id %>
	        </div>
	        <div class="actions">
	        	<%= f.submit %>
	        </div>
	      <% end %>
	      <button class="cancel-creation">Cancel</button>
	</div>
	<button class="new-row-btn">New Endpoint</button>
	<br>
	<br>
	<br>
<% end %>

app/views/resources/create.js.erb
<% if @resource.new_record? %>
  $('input#resource_name').effect('highlight', { color: 'red' });
<% else %>
  $('div#resources').append("<%= escape_javascript(render @resource) %>");
  $('div#<%= dom_id(@resource) %>').effect('highlight');
<% end %>

app/views/resources/destroy.js.erb
$("div#<%= 'resource_' + @resource.id.to_s %>").fadeOut();

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<% javascript_include_tag "application" %>

<h1>Restful API</h1>

<div id="global-container">
  <div id="model-container">
      <table>
        <caption class="model-title">
          Models
        </caption>
        <thead>
        <tr>
          <th>
            Model
          </th>
          <th>
            Description
          </th>
          <th>
          </th>
        </tr>
        </thead>
        <tbody class="models">
            <%= render @project.models %>
        </tbody>
      </table>
      <div class="new-form-container hidden">
        <%= form_for([@project,Model.new], remote:true, authenticity_token: form_authenticity_token) do |f| %>
            <div class="field">
              <%= f.text_field :method_type , class: "type-input-field" , placeholder: "Method Type" %>
              <%= f.text_field :url , class: "url-input-field" , placeholder: "URI" %>
              <%= f.text_area :description , class: "description-input-field" , placeholder: "Description" %>
            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
        <% end %>
        <button class="cancel-creation">Cancel</button>
      </div>
      <button class="new-row-btn">New Model</button>
      <br>
      <br>
      <br>
  </div>


  <div class="new-form-container hidden">
      <%= form_for(Resource.new, remote:true) do |f| %>
          <div class="field">
            <%= f.text_field :name %>
            <%= f.text_field :description %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
      <% end %>
      <button class="cancel-creation">Cancel</button>
  </div>
  <button class="new-row-btn">New Resource</button>
  <div id="resources">
    <%= render @resources %>
  </div>
</div>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/resources/update.js.erb
$("<%= '#resource-' + @resource.id.to_s %> .name").html("<%= @resource.name %>")
$("<%= '#resource-' + @resource.id.to_s %> .description").html("<%= @resource.description %>");
$("<%= '#resource-' + @resource.id.to_s %>").removeClass('hidden');
$("<%= '#edit-resource-' + @resource.id.to_s %>").addClass('hidden');