config/routes.rb
Resty::Application.routes.draw do
  

  root :to => 'home#show'

  resources :projects do

    resources :resources
    
    resources :endpoints do
      resources :parameters
    end

    resources :models do
      resources :parameters
    end

  end

  resources :users

  

end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
	belongs_to :param_container, polymorphic: true
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  before_action :set_param_container
  before_action :set_parameter, only: [:show, :edit, :update, :destroy]

  # GET /parameters
  # GET /parameters.json
  def index
    @parameters = @param_container.parameters.all
  end

  # GET /parameters/1
  # GET /parameters/1.json
  def show
  end

  # GET /parameters/new
  def new
    @parameter = Parameter.new
  end

  # GET /parameters/1/edit
  def edit
  end

  # POST /parameters
  # POST /parameters.json
  def create
    @parameter = @param_container.parameters.new(parameter_params)

    respond_to do |format|
      if @parameter.save
        format.html { redirect_to [@project, @param_container, @parameter], notice: 'Parameter was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@project, @param_container, @parameter] }
      else
        format.html { render action: 'new' }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PATCH/PUT /parameters/1
  # PATCH/PUT /parameters/1.json
  def update
    respond_to do |format|
      if @parameter.update(parameter_params)
        format.html { redirect_to [@project, @param_container, @parameter], notice: 'Parameter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /parameters/1
  # DELETE /parameters/1.json
  def destroy
    @parameter.destroy
    respond_to do |format|
      format.html { redirect_to parameters_url }
      format.json { head :no_content }
      format.js
    end
  end

  private

    def set_param_container
      @project = Project.find(params[:project_id])
      if params.has_key?(:endpoint_id)
        @param_container = @project.endpoints.find(params[:endpoint_id])
      end
      if params.has_key?(:model_id)
        @param_container = @project.models.find(params[:model_id])
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_parameter
      @parameter = @param_container.parameters.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parameter_params
      params.require(:parameter).permit(:name, :optional, :example_value, :param_container_id, :param_container_type, :description, :project_id)
    end
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/views/parameters/_form.html.erb
<%= form_for(@parameter) do |f| %>
  <% if @parameter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parameter.errors.count, "error") %> prohibited this parameter from being saved:</h2>

      <ul>
      <% @parameter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :optional %><br>
    <%= f.check_box :optional %>
  </div>
  <div class="field">
    <%= f.label :example_value %><br>
    <%= f.text_field :example_value %>
  </div>
  <div class="field">
    <%= f.label :endpoint_id %><br>
    <%= f.number_field :endpoint_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parameters/_parameter.html.erb
<tr class="data-row editable" id="<%= 'parameter-' + parameter.id.to_s %>">
	<td class="parameter-name"><%= parameter.name %></td>
	<td class="parameter-description">
	    <%= replace_model_link(parameter.description, @project).html_safe %>
	</td>
    <td>
      <div class="edit-btn-div v-hidden">
        <%= link_to 'Edit', 'javascript:;', class: 'edit-btn' %><br>
        <%= link_to 'Delete', [@project, @param_container, parameter], method: :delete, remote: true %>
      </div>
    </td>
</tr>
<tr class="data-row hidden editable" id="<%= 'edit-parameter-' + parameter.id.to_s %>">
  <td>
      <%= form_for([@project, @param_container, parameter], remote:true, authenticity_token: form_authenticity_token) do |f| %>

          <div class="field">
            <%= f.text_field :name , class: 'name-input-field' , placeholder: 'Name'%>
            <%= f.text_field :example_value , class: 'example-input-field' , placeholder: 'Example Value'%>
            <%= f.text_area :description , class: 'description-input-field' , placeholder: 'Description'%>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
      <% end %>
      <button class="cancel-update">Cancel</button>
  </td>
</tr>

app/views/parameters/create.js.erb
<% if @parameter.new_record? %>
  $('input#endpoint_name').effect('highlight', { color: 'red' });
<% else %>
  $('#parameters').append("<%= escape_javascript(render @parameter) %>");
  $('div#<%= dom_id(@parameter) %>').effect('highlight');
<% end %>

app/views/parameters/destroy.js.erb
$("tr#<%= 'parameter-' + @endpoint.id.to_s + '-' + @parameter.id.to_s %>").fadeOut();

app/views/parameters/edit.html.erb
<h1>Editing parameter</h1>

<%= render 'form' %>

<%= link_to 'Show', @parameter %> |
<%= link_to 'Back', parameters_path %>

app/views/parameters/index.html.erb
<h1>Listing parameters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Optional</th>
      <th>Example value</th>
      <th>Endpoint</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @parameters.each do |parameter| %>
      <tr>
        <td><%= parameter.name %></td>
        <td><%= parameter.optional %></td>
        <td><%= parameter.example_value %></td>
        <td><%= parameter.endpoint_id %></td>
        <td><%= link_to 'Show', parameter %></td>
        <td><%= link_to 'Edit', edit_parameter_path(parameter) %></td>
        <td><%= link_to 'Destroy', parameter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parameter', new_parameter_path %>

app/views/parameters/new.html.erb
<h1>New parameter</h1>

<%= render 'form' %>

<%= link_to 'Back', parameters_path %>

app/views/parameters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @parameter.name %>
</p>

<p>
  <strong>Optional:</strong>
  <%= @parameter.optional %>
</p>

<p>
  <strong>Example value:</strong>
  <%= @parameter.example_value %>
</p>

<p>
  <strong>Endpoint:</strong>
  <%= @parameter.endpoint_id %>
</p>

<%= link_to 'Edit', edit_parameter_path(@parameter) %> |
<%= link_to 'Back', parameters_path %>

app/views/parameters/update.js.erb
$("<%= '#parameter-' + @parameter.id.to_s %> .parameter-name").html("<%= @parameter.name %>")
$("<%= '#parameter-' + @parameter.id.to_s %> .example_value").html("<%= @parameter.example_value %>")
$("<%= '#parameter-' + @parameter.id.to_s %> .parameter-description").html("<%= @parameter.description %>");
$("<%= '#parameter-' + @parameter.id.to_s %>").removeClass('hidden');
$("<%= '#edit-parameter-' + @parameter.id.to_s %>").addClass('hidden');